name: Scan

on: push

jobs:
  scan:
    permissions:
      security-events: write
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run endorctl
      uses: endorlabs/github-action@e983ae04473a3fcda4db43190ad55c57118b5ca0
      with:
        namespace: "diamantis"
        api: "https://api.staging.endorlabs.com"
        enable_github_action_token: "true"
        sarif_file: findings.sarif

    - name: Upload SARIF to github
      uses: github/codeql-action/upload-sarif@9885f86fab4879632b7e44514f19148225dfbdcd
      with:
        sarif_file: findings.sarif
